library(Azimuth)
library(biomaRt)
library(colorRamp2)
library(ComplexHeatmap)
library(data.table)
library(dplyr)
library(future)
options(future.globals.maxSize = 8000 * 1024^2)
library(GeneOrthology)
library(ggplot2)
library(gridExtra)
library(magrittr)
library(tidyverse)
library(orthologsBioMART)
library(patchwork)
library(RColorBrewer)
library(Seurat)
library(stringr)
library(UCell)

